### ISSUE TITLE
Latest versions of bamnostic are not being found.

### ISSUE THREAD

**Issue by ericmjl** [conda-forge/bamnostic-feedstock#5]
cc: @betteridiot @ocefpaf @jakirkham @msarahan 

When searching for for bamnostic (<code>conda search bamnostic</code>), the latest two versions are not found on conda-forge.

```
$ conda search bamnostic
Loading channels: done
# Name                  Version           Build  Channel
bamnostic              0.4.2b13            py_0  conda-forge
bamnostic                 0.8.4            py_0  conda-forge
bamnostic                 0.8.5            py_0  conda-forge
```

Version 0.8.8 should be available, as the PR #3 was merged 8 days ago already, unless this is an issue with the CIs? Please let us know (@betteridiot and myself) if there's something we can do here.

**Comment by betteridiot** [comment]
As of 4c038d22a40e5ab9af4664cc80af1607f2c39c91, versioning is fixed to reflect current 0.8.9 version

**Comment by ocefpaf** [comment]
I think that is already fixed.

```
> conda search --channel conda-forge bamnostic
Loading channels: done
# Name                  Version           Build  Channel             
bamnostic              0.4.2b13            py_0  conda-forge         
bamnostic                 0.8.4            py_0  conda-forge         
bamnostic                 0.8.5            py_0  conda-forge         
bamnostic                 0.8.9            py_0  conda-forge
```

**Comment by jakirkham** [comment]
Yeah the latest version just went up (it [was building]( https://circleci.com/gh/conda-forge/bamnostic-feedstock/8 )). However 0.8.8 being missing is concerning. It appears the [build ran]( https://circleci.com/gh/conda-forge/bamnostic-feedstock/6 ), but it failed to upload as it didn't have access to the token.

**Comment by betteridiot** [comment]
I guess the concern I had was that there were multiple versions pushed to PyPI that were not built/updated [(0.8.6b1, 0.8.7b*, and 0.8.8)](https://pypi.org/project/bamnostic/#history)

**Comment by jakirkham** [comment]
So there were no PRs to add the betas. If there is interest in publishing betas, we can discuss the workflow for that. It differs from the standard workflow of stable releases slightly though.

**Comment by betteridiot** [comment]
Okay, I figured beta builds had something to do with that.

**Comment by betteridiot** [comment]
As per 4c038d22a40e5ab9af4664cc80af1607f2c39c91, I think this issue is closed. I will have to keep an eye on it in the future and see if the BINSTAR_TOKEN problem comes up again. Thank you

**Comment by jakirkham** [comment]
Ah, I missed something crucial here. The build I linked was a PR build. So not having the token is expected. Looks like CircleCI simply didn't run on the merge commit related to that release. This is still concerning, but for a different reason. Will look into it a bit more.

**Comment by jakirkham** [comment]
Looks like the webhook request for that commit failed with a 503. It's unclear why it failed as nothing was specified. Doesn't appear like there were any issues with GitHub that day. Have retriggered that specific request and it created [this build]( https://circleci.com/gh/conda-forge/bamnostic-feedstock/9 ), which is queued.
